### ISSUE TITLE
The release tag is placed on the wrong commit

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/action-publish-release#94]
When a release is published, the GitHub release is created without setting a target. It defaults to targeting the `main` branch. This will result in the release tag being placed on the wrong commit if any PRs were merged since the release candidate was merged.

We should set a target when creating the GitHub release, so that it's always set on the correct commit

**Comment by Gudahtt** [comment]
The `--target` command can be added here: https://github.com/MetaMask/action-publish-release/blob/0c93dad610fd79ff391eeae2a7c9591fb31e722b/scripts/create-github-release.sh#L33

**Comment by desi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/action-publish-release/94?planning-poker) with Zenhub @cryptodev-2s @kanthesha @MajorLift @mcmire
